### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by ctf0** [hankchizljaw/beedle-vue-demo#1]
i wanted to test beedle so i created a very small demo of a 2 comps and a store like so 

- sore
```js
// store.js

import Store from 'beedle'

export default new Store({
    actions: {
        addData(context, payload) {
            context.commit('addToFormData', payload)
        }
    },
    mutations: {
        addToFormData(state, {key, val}) {
            state.formData[key] = val
            return state
        }
    },
    initialState: {
        formData: []
    }
})
```

- input comp
```js
<template>
    <input type="text" @input="getName">
</template>

<script>
import store from './store'

export default {
    methods: {
        getName(e) {
            store.dispatch('addData', {
                key: e.target.name,
                val: this.input
            })
        }
    },
}
</script>
```

- form comp
```js
<template>
    <ul>
        <li v-for="(val, key) in inputsData" :key="key">
            {{ key }}: {{ val }}
        </li>
    </ul>    
</template>

<script>
import store from './store'

export default {
    data() {
        return {
            inputsData: store.state.formData
        }
    }
}
</script>
```

- main.js
```js
new Vue({
    el: '#app',
    components: {
        inputComp: require('./input.vue'),
        formComp: require('./form.vue')
    },
    render(createElement) {
        return createElement(
            'div',
            {},
            [
                createElement(inputComp),
                createElement(formComp)
            ]
        )
    }
})
```

now the problem is that `inputsData` never gets updated, so am not sure if this a setup issue, a usage issue or a problem with the package ?

**Comment by Andy-set-studio** [comment]
Ideally, a Vue adapter would be created in the long term to help this. The examples in this repo assign `store.state` to the Vue component's `data` object which Vue picks up. This isn't a perfect solution though.

## Options:
- Find a way of tapping into the [subscribe](https://beedle.hankchizljaw.io/reference/store-class.html#subscribe-callback) event (this is probably the best way to tackle a Vue adapter)
- Create computed properties that return `data.state` items:

### Example of point 2:
```javascript
data() {
  return {
    state: store.state
  };		
}
```

#### Computed prop
```javascript 
formData() {
  return this.state.formData;
}
```

This may or may not work. It's _just_ an idea :)

**Comment by ctf0** [comment]
i actually already tried with the `subscribe` inside a computed prop and all i got was `true`, no data updates are being picked up

on a side note, i thought following the demo examples are enough without the need for a specific wrapper or an adapter.

**Comment by Andy-set-studio** [comment]
These are _just_ examples of how you could theoretically use Beedle with a popular framework. They're certainly not fully-fledged.
